name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir build && cd build && cmake -DBUILD_TESTING=ON -DCMAKE_BUILD_DIR=Debug ..
    - name: make
      run: cd build && make
    - name: test
      run: cd build && ctest
